version: '3.3'
services:
 db: 
  image: mysql
  network_mode: host
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: test
    MYSQL_DATABASE: meals
    MYSQL_PASSWORD: ''